data_dir = "/tmp/data"
db_engine = "sqlite"
metadata_dir = "/tmp/meta"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "$(openssl rand -hex 32)"

[s3_api]
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"
s3_region = "garage"

[s3_web]
bind_addr = "[::]:3902"
index = "index.html"
root_domain = ".web.garage.localhost"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
admin_token = "$(openssl rand -base64 32)"
api_bind_addr = "[::]:3903"
metrics_token = "$(openssl rand -base64 32)"
